name = "moajim"
main = "worker/index.ts"
compatibility_date = "2025-09-27"

# Pages 빌드 출력 디렉토리
pages_build_output_dir = "dist"

[observability]
enabled = true

# 추후 필요시 설정
# [placement]
# mode = "smart"

# [vars]
# MY_VARIABLE = "production_value"
