name = "moajim-api"
main = "worker/index.ts"
compatibility_date = "2025-09-27"

# moajim.com/api 라우트 설정
routes = [
  { pattern = "moajim.com/api/*", zone_name = "moajim.com" }
]

[observability]
enabled = true

# D1 Database
[[d1_databases]]
binding = "DB"
database_name = "moajim-db"
database_id = "23ba175f-add7-4888-b9df-faee2a781d9d"
